[package]
distribution = "2201.9.0"
org = "ballerinax"
name = "openai.finetunes"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [] # TODO: Add keywords
icon = "icon.png" # TODO: Add icon
repository = "https://github.com/KATTA-00/module-ballerinax-openai-finetunes"

[build-options]
observabilityIncluded = true