[package]
distribution = "2201.9.0"
org = "ballerinax"
name = "openai.finetunes"
version = "1.0.7"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AI/Fine-tunes", "OpenAI", "Cost/Paid", "Files", "Models", "Vendor/OpenAI"]
icon = "icon.png"
repository = "https://github.com/KATTA-00/module-ballerinax-openai-finetunes"

[build-options]
observabilityIncluded = true