[package]
distribution = "2201.9.0"
org = "ballerinax"
name = "openai.finetunes"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
icon = "icon.png"
repository = "https://github.com/KATTA-00/module-ballerinax-openai-finetunes"

[build-options]
observabilityIncluded = true